title = "Eckankar in Australia"
baseURL = ""
languageCode = "en-us"
theme = "ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

 [params]
custom_css = ["css/custom.css","css/custom2.css"]

  favicon = ""
  description = "find Events in Australia."
 # facebook = ""
 # twitter = "https://twitter.com/GoHugoIO"
 # instagram = ""
 # youtube = ""
  #github = ""
 # gitlab = ""
 # linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-white"
  featured_image = "images/lotus3a.jpg"
  recent_posts_number = 20

  # Start the server  clear;clear; hugo server -D --buildDrafts --watch
  # Create Production:
  #HUGO_ENV=production hugo  -b"http://localhost/sites/public/"  --cleanDestinationDir 
